info:
  contact: {}
paths:
  /model/{id}:
    get:
      consumes:
      - application/json
      description: gets models using its id
      parameters:
      - description: Model ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get model by its id
      tags:
      - models
  /models/:
    get:
      description: gets all models
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get all models
      tags:
      - models
swagger: "2.0"
