networks:
  frontend:
  backend:
    internal: true
services:
  web:
    networks:
      - frontend
    build:
      context: ./frontend/model-hub/
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${API_URL}
    restart: unless-stopped
    depends_on:
      - api

  api:
    networks:
      - backend
      - frontend
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      # API config
      MODEL_HUB_PORT: "8080"
      DEV_MODE: false

      # DB connection details
      DB_HOSTNAME: db
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL_MODE: require

      # auth details
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
    restart: unless-stopped
    expose:
      - "8080"
    

  db:
    networks:
      - backend
    image: postgres:18-alpine
    entrypoint: ["sh", "/docker-entrypoint-ssl.sh"]
    command:
      - postgres
      - -c
      - ssl=on
      - -c
      - ssl_cert_file=/var/lib/postgresql/certs/server.crt
      - -c
      - ssl_key_file=/var/lib/postgresql/certs/server.key
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/18/docker
      - ./db/docker-entrypoint-ssl.sh:/docker-entrypoint-ssl.sh:ro
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ${DB_SSL_CRT_PATH}:/run/certs-ro/server.crt:ro
      - ${DB_SSL_KEY_PATH}:/run/certs-ro/server.key:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    expose:
      - "5432"

  nginx:
    networks:
      - frontend
    image: nginx:1.29-alpine
    environment:
      - SSL_CERT_PATH=${SSL_CRT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro
      - ${SSL_CRT_PATH}:/etc/nginx/certs/cert.crt:ro
      - ${SSL_KEY_PATH}:/etc/nginx/certs/cert.key:ro
    restart: unless-stopped
    depends_on:
      - web
      - api

volumes:
  db_data:
