Dockerfile.web
# Base image 
FROM node:22

# Set working directory
WORKDIR /webapp

# Install dependencies
COPY frontend/model-hub/package*.json ./
RUN npm install

# Bundle app source
COPY frontend/model-hub .

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]