$env:OPENDI_MODEL_HUB_ADDRESS = "localhost"
$env:OPENDI_MODEL_HUB_PORT = "8080"
$env:OPEN_DI_DB_NAME = "open_di_model_hub"
$env:OPEN_DI_DB_PORT = "3306"
$env:OPEN_DI_DB_HOSTNAME = "localhost"
$env:OPEN_DI_DB_PASSWORD = "Googleplx1!!"
$env:OPEN_DI_DB_USERNAME = "root"

Write-Output "Environment variables set for the current session:"
Write-Output "OPENDI_MODEL_HUB_ADDRESS = $env:OPENDI_MODEL_HUB_ADDRESS"
Write-Output "OPENDI_MODEL_HUB_PORT = $env:OPENDI_MODEL_HUB_PORT"
Write-Output "OPEN_DI_DB_NAME = $env:OPEN_DI_DB_NAME"
Write-Output "OPEN_DI_DB_PORT = $env:OPEN_DI_DB_PORT"
Write-Output "OPEN_DI_DB_HOSTNAME = $env:OPEN_DI_DB_HOSTNAME"
Write-Output "OPEN_DI_DB_USERNAME = $env:OPEN_DI_DB_USERNAME"