# Base image 
FROM node:24-alpine

# Set working directory
WORKDIR /webapp

# Install dependencies
COPY ./package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Start the application
CMD ["npm", "start"]
