# Stage 1: build
FROM node:24-alpine AS builder

WORKDIR /webapp

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
RUN npm run build

# Stage 2: serve
FROM nginx:1.29-alpine
COPY --from=builder /webapp/build /usr/share/nginx/html

EXPOSE 80
